### ISSUE TITLE
Error-java.io file not found

### ISSUE THREAD

**Issue by Abhishekrwt1** [cttricks/xTinyDB#1]
I love your hard work .. 

i am getting error while trying to get and store value by mobile 
 java.io.filenot found exception; https;//test.000webhostapp.com/xTinyDB/v2/getValue.php and /storeValue.php how to fix this problem 

and while i am trying to open https;//test.000webhostapp.com/xTinyDB/v2/getValue.php in laptop then it showing me error

Warning: file_put_contents(https://test.000webhostapp.com/xTinyDB/v2/bucket-locators.json): failed to open stream: HTTP wrapper does not support writeable connections in /storage/ssd4/451/17193451/public_html/xTinyDB/v2/dbInfo.php on line 18

Notice: Undefined index: Authorization in /storage/ssd4/451/17193451/public_html/xTinyDB/v2/dbInfo.php on line 23
{"status":"Failed","msg":"invalid access key"}

**Comment by cttricks** [comment]
The server where you have hosted xTinyDB is not live. Kindly host it on a stable server.
The issue is, it is targeting files from outside of public_html, check your hosting server configuration for that.
