### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Abhishekrwt1** [cttricks/xTinyDB#2]
https://github.com/cttricks/xTinyDB/issues/1#issuecomment-875338374
Dear sir you said this above and now i am not using free hosting and using stable hosting.. still i am getting error..

Can you little give me information what type configuration i have to do in my hosting ..you said before that i am getting error because hosting is trying to target file from outside ..so can u please help me and can you little more explain that what configuration have to do ..
I really need this DB

**Comment by cttricks** [comment]
Hi 
Thanks for your patience.

There is no special configuration required. Simply Host the files on your server and make a small changes on dbinfo.php
